### ISSUE TITLE
extension doesn't work on google page

### ISSUE THREAD

**Issue by themrstone24** [Christoph142/modern-scroll#105]
The extension don't seems to work on the google result page.
![image_2020-11-28_111842](https://user-images.githubusercontent.com/32277189/100499789-79d20200-316b-11eb-9ac5-d25bfa8afbdb.png)

**Comment by Christoph142** [comment]
It does for me. Did you disable the extension on any Google page via the context menu?

**Comment by themrstone24** [comment]
I tried everything I can but it's doesn't seems to work.
I will keep trying.
What did you call "context menu" ?

**Comment by themrstone24** [comment]
EDIT:

It's working i am just stupid, I don't have setup the extension correctly in Opera's settings.
It was my fault sorry for the issue opening.
