### ISSUE TITLE
please delay the bookmarks / headings

### ISSUE THREAD

**Issue by filbo** [Christoph142/modern-scroll#106]
The bookmarks / headings setting makes it difficult to use the modern-scroll options within its own menu, pulled down from the browser toolbar menu button.  The option checkboxes are near the right edge (I was having a hard time with the 'Save' icon).

This also just generally makes it difficult to use any part of a window which is near its far right edge.

I'm aware I can avoid popping these up if I 'simply' don't touch the window's scrollbar.  But I am not habitually that careful: my typical mouse approach probably looks like a big curve which somewhat overshoots the target, then pulls back.  Having crossed the scrollbar, even for an instant, blats a bunch of scrollbar bookmark headings over the right side of the page, over the page widgets I was actually trying to interact with.

The bookmark buttons seem to have around a 1500ms fadeout after mousing *away* from the scrollbar.  Please add a corresponding *fade in* timer.  Something like: after the mouse touches the scrollbar, track how long it stays within some delta distance (?50px?) of the scrollbar.  If it stays within for 750ms, bring up the bookmarks.

A way to dismiss the bookmarks would also be helpful.  e.g.: waggle the mouse left-right-left-right in that area while they're up -- with motions large and sharp enough to be intentional.  Stay dismissed until mouse has left and reentered the area.

**Comment by filbo** [comment]
I've disabled the bookmarks feature for now.  Please comment if this is improved.

**Comment by Christoph142** [comment]
I get the issue, but I think it's rather an edge case. Normally there is no UI that close to the border.
If you're spending time configuring the extension excessively you'd normally open it in a tab and there's space. If you change a single setting it's not that big of a deal. And if you really want to change a lot of settings in the popup, you could temporarily disable the bookmarks while you're adjusting to do so.

**Comment by filbo** [comment]
Maybe an option to specifically disable bookmarks + headings in the extension bar menu?  They're rather intrusively big compared to the menu.

It isn't that I'm 'spending time configuring the extension excessively'; rather, that almost every time I try to do anything with the extension bar menu, I bonk into this and am forcefully reminded of the problem.

Oh -- I just noticed that bookmarks & headings don't appear at all on the full-page options screen!  Suppose you flip that -- have them appear there, where they're far less intrusive and far less likely to be activated by mistake; and not at all on the menu when embedded in an extension bar icon?
