### ISSUE TITLE
PgUp / PgDn may omit sections of page content

### ISSUE THREAD

**Issue by filbo** [Christoph142/modern-scroll#107]
Does modern scroll exert any influence over how the keyboard keys PgUp / PgDn are handled?

I ask for two reasons:

(1) it seems like it does, in a good way -- it feels like PgUp / PgDn are much faster, more of an instant redraw than a slow-wave-lurch like I expect.  ('slow' like I can perceive the redraw happening over maybe 100ms of realtime)

(2) I'm currently annoyed at a web page for setting itself up (somehow) so that PgDn has negative overlap.  Instead of, let's say, 2 lines which were previously at the bottom of the window now being at the top, instead it leaps forward about 1 whole viewport *plus* a line.  So I more or less need to hit 'PgDn, UpArrow' every time if I want a smooth viewing experience.

... Therefore I'm wondering if modern scroll could take control of that; provide some sort of override control of PgUp/Dn overlap.

**Comment by Christoph142** [comment]
modern scroll indeed alters the scrolling with the keyboard if you have the feature turned on (it is by default).
However, if that particular page is manipulating it nonetheless there's nothing that can be done about it. Your best bet is contacting the site owner instead and making them aware of this issue.

**Comment by filbo** [comment]
I think that changing your functions scroll_PageDown(), scroll_PageUp() to use some value other than -window.InnerHeight would address my problem.

Exactly what 'value other than' is not 100% clear to me.  The proposal is to give some sort of control here, but I'm not sure what.  Probably one of these:

a. 'Add ___ pixels overlap to PgUp/PgDn'   [ ==> - (InnerHeight - pgupdn_overlap_pixels) ]
b. 'Add __% overlap to PgUp/PgDn'          [ ==> - (InnerHeight * pgupdn_overlap_scaler) ... where scaler = (100 - pct_overlap) / 100 ]

... and probably allow negative values for the setting, because who knows what peculiar application someone might have for that.

Looking at other uses of InnerHeight, I couldn't decide if any of them ought to also be conditioned by this user setting.  My quick glance suggested 'no', but I didn't study them that hard.

Where does the problem come from?

I think any site with either of these features would clash with the use of InnerHeight for this:

(A) permanent top/bottom bars, and the scrolling content fits between

(B) the whole page is scrollable, but some top and/or bottom area is hidden behind some sort of overlay

I believe that native browser pgup/dn would handle (A) correctly, but not (B).  However if native pgup/dn have some inherent overlap, and the obstructing overlay is small, (B) might be OK.

(A) is a pretty standard site design and perhaps needs handling beyond just a modified use of InnerHeight -- you may need to be extracting the scrollable height of the active area.

(B) is arguably bad site design, but it's out there and some way to accommodate it would be helpful.

Thanks...

**Comment by filbo** [comment]
I just noticed an easily observed site with this problem: youtube.  Find any youtube video with enough comments to need scrolling -- e.g. https://www.youtube.com/watch?v=emkJ0A7IfkY -- hit PgUp/PgDn, observe the non-overlapping viewports.  Specifically, it seems to be eating about 3 lines of text.  Which, not coincidentally, is the size of the black non-scrolling top bar.

**Comment by filbo** [comment]
Another fine example page is https://github.com/Christoph142/modern-scroll/issues/107

**Comment by Christoph142** [comment]
Thanks for investigating this. I can reproduce it. I'll have a look at it. 🙌

**Comment by Christoph142** [comment]
I spent countless hours on this. In the end the only thing I can do is restore browser's default behavior for physical pageUp and pageDown keys. To my knowledge this can't be fixed when clicking the background bars.
If anyone knows better here, please let me know.

**Comment by Droyk** [comment]
Hey @Christoph142, instead of closing this issue open this issue and put a tag "can't fix/don't know how to fix!" 
even if you don't want to open it please add those tags for visibility so that someone who knows about it can offer some help!
if a developer who is going by your extension can see the issue & if they know how can help! 
also, please mention all of the limitations that you've encountered & the issues that you can't fix on [the main page](https://github.com/Christoph142/modern-scroll) for visibility. any users coming by to report the issue can see if their issue is on the list or not will save their time!
