### ISSUE TITLE
"Not available anymore"

### ISSUE THREAD

**Issue by survivor303** [Christoph142/modern-scroll#110]
Google webstore says in the download link "Not available anymore".

https://chrome.google.com/webstore/detail/modern-scroll/ejonaglbdpcfkgbcnidjlnjogfdgbofp

**Comment by Christoph142** [comment]
The link works fine for me.

**Comment by survivor303** [comment]
Oh, it can be that i use Microsoft Edge 😳

And today i learn that you added it to Edges addon page too. Thank you.
