### ISSUE TITLE
Doesn't work well with trackpad/touchpad zoom.

### ISSUE THREAD

**Issue by muizzsiddique** [Christoph142/modern-scroll#111]
Zooming into a page using a trackpad/touchscreen zooms into the "window" (not the page) which also means the scroll bar zooms in and out and can go off-screen if you zoom anywhere to the left of the scroll bar. I don't know how you would fix this.

**Comment by Christoph142** [comment]
I'm afraid there's nothing I can do about that. This kind of zoom is done in a way that prevents any layout change. It's impossible to counter by design.
