### ISSUE TITLE
Update version of the extension on edge browser

### ISSUE THREAD

**Issue by NguyenASang** [Christoph142/modern-scroll#161]

**Comment by Christoph142** [comment]
Already uploaded.

**Comment by NguyenASang** [comment]
![image](https://user-images.githubusercontent.com/87893636/132949754-93d7918b-08ac-48b2-b865-b286cd77f2ca.png)

**Comment by Christoph142** [comment]
All uploads are getting checked by Microsoft. They usually take a few days.
