### ISSUE TITLE
Add an option to disable annoying popups

### ISSUE THREAD

**Issue by Glaived** [Christoph142/modern-scroll#179]
[More info here](https://github.com/Christoph142/modern-scroll/discussions/181)

**Comment by Christoph142** [comment]
Yeah, I get that it can get in the way if triggered every month. I'm annoyed by it myself. 😅 
I think I'm going to double the interval every time the dialog gets shown, i.e. first time after 1 month, than after 3, 6 and so on.

**Comment by Christoph142** [comment]
Yeah, I know, it's hard to be confronted with a tab every once in a while which states that developing an extension takes countless hours and that it is done entirely for free and some kind of support would be nice... You can remove it locally in your copy if it's too much of a hassle.🙄
But a little bit of appreciation would be welcomed!

**Comment by Glaived** [comment]
My reaction is due to the fact that you do not answer the problems mentioned:
- The _hello_again_ feature is literally useless (see code). Does it need to be improved in the future to get a concrete use, like making statistics on user satisfaction? Am I wrong about the current state of _hello_again_, and that it would be of concrete interest, if so what?
- You did not argue about my proposal: « Add an option to disable annoying popups »

___

> it's hard to be confronted with a tab every once in a while which states that developing an extension takes countless hours and that it is done entirely for free and some kind of support would be nice...

Something I have already mentioned, and that it is quite normal to invite the user to support this project or your other projects.

> Although it is good to remember that it is possible to support the development of this extension.

___

> You can remove it locally in your copy if it's too much of a hassle.🙄

An easy way to ignore a problem, without bringing an elegant solution.

> But a little bit of appreciation would be welcomed!

And that is exactly what I am doing with my contribution to your project.
___

The problem is how to encourage the user to support your projects without making an intrusive solution (popup) in the user experience. What I proposed was to add an option that would disable these popups.
The interest is, that by default, the user will always be invited to support you, and especially to be warned that there are solutions to support you. But in case the user does not have this wish, **it is in no way interesting to insist via an intrusive solution.**
Moreover, this solution is at the user's choice and brings few modifications to the project.

Another solution would be to make it less intrusive.

I would like to finish by reminding you that thousands (many more) of open-source browser extensions are developing non-intrusive solutions for us to support. This is beneficial for both end users and developers.
