### ISSUE TITLE
Cannot scroll websites on Immersive Reader Mode with touch on MS Edge

### ISSUE THREAD

**Issue by miguedevel** [Christoph142/modern-scroll#182]
Steps to reproduce:
-With Modern scroll enabled, visit https://en.wikipedia.org/wiki/Wikipedia for example.
-Click on the Immersive Reader Mode icon on the address bar or press F9 key.
-Try to scroll the article with touchscreen gestures. It won't scroll. If the extension is disabled, then scrolling works as expected.

**Comment by Christoph142** [comment]
Hi @miguedevel, I tried the steps you wrote, but it works fine for me. Edge creates a read:// URL from the page and doesn't load extensions for me on that URL. I see the standard scrollbar and scrolling works normal (as if the extension wasn't installed at all).
Any special permissions / settings you enabled? Does Edge have something along the lines of "enable extension on internal pages"...?

**Comment by miguedevel** [comment]
I forgot a detail; this is on Edge Dev, currently at version 98.0.1108.13.
I tested the scenario on Edge stable and the issue does not occur.

**Comment by Christoph142** [comment]
Probably a bug in Edge then? Please keep an eye on it and let me know if it makes it to beta / stable. 😉

**Comment by miguedevel** [comment]
It seems it was a bug in Edge. The current Dev, now at version 99.0.1131.3, does not exhibit this issue. Though I do have to mention that since the version of my previous comment, extensions ARE being loaded now on read:// pages as the scrollbar is being stylized.

**Comment by Christoph142** [comment]
Interesting. Thanks for letting me know. 🙂
