### ISSUE TITLE
Can't scroll on music.163.com

### ISSUE THREAD

**Issue by JeffeyChou** [Christoph142/modern-scroll#190]
Just as the title mentioned, I can't scroll the site when using this expansion. But when I unloaded the expansion, everything returned normal.
    Can the author of the expansion fix this problem? 
    Respect!

**Comment by Christoph142** [comment]
This should be fixed in 4.1.2. Did you update already?
It's available in the Chrome Web Store. Not yet in Edge and Opera's catalogues.

**Comment by JeffeyChou** [comment]
Aye, it seems I haven't update my expansion version.
And the latest version works pretty well.
Thank you
