### ISSUE TITLE
box scroll compatible

### ISSUE THREAD

**Issue by richex-cn** [Christoph142/modern-scroll#209]
Reproduction: https://codepen.io/richex/pen/ZEoJxzK

> moden scroll: 4.2.2
> Chrome: 105.0.5195.127

If the scroll bar is on the DOM box:

![Snipaste_2022-09-22_09-49-21](https://user-images.githubusercontent.com/25103518/191640588-8deab465-22de-4fee-a256-2ab1c614c1fd.png)

It's normal style:

![Snipaste_2022-09-22_09-49-10](https://user-images.githubusercontent.com/25103518/191640572-9a0ec872-7c10-42c2-9a2c-218b1fe8c921.png)

**Comment by Christoph142** [comment]
Hi @richex-cn, thanks for reporting this! It's fixed in https://github.com/Christoph142/modern-scroll/commit/ca71958887692ae8b37c6de501ae6c943f548ee7 :)
