### ISSUE TITLE
causes scrollbars on exercism.org to disappear

### ISSUE THREAD

**Issue by filbo** [Christoph142/modern-scroll#212]
When Modern Scroll is enabled, scrollbars are missing on exercism.org.

I've verified this with default MS settings.  However there is some weirdness about changing settings vs. reloading vs. enabling/disabling MS on the specific site.  Some effort / fooling around may be required to consistently reproduce the issue.

Note that an exercism.org login is *not needed*.  You can get to a sample exercise without it (tested in 'incognito').

1. open https://exercism.org/tracks/javascript/exercises/regular-chatbot
2. make your browser window as narrow as possible.  Exercism will prevent it from getting below about 500 pixels
3. scroll down to the first code box (starts with `isValidCommand("Chatbot ...`)
4. due to the narrow window, the code in this box should be nearly twice as wide as the box; the box should have a scrollbar
5. if MS is active, the scrollbar is missing
6. **if it does not reproduce**: go into MS settings, load Default; reload the Exercism page; disable MS for this site; re-enable MS for this site; reload the Exercism page

![ms-1](https://user-images.githubusercontent.com/3022180/208225731-55cba38d-6143-4904-9891-6a5f5980b76f.png)

Modern Scroll 4.2.2 from Opera 'store' (ID 'eiinejdcihhdbdbipfapahmjndejdpjb')
Opera opera-developer 88.0.4401.0
LinuxMint 17.3 based on Ubuntu 14.04 'Trusty'
Linux '4.4.0-148-lowlatency #174~14.04.1-Ubuntu SMP PREEMPT'

I'm aware my system is appallingly out of date :)  Don't think it relates to the issue.

Two other issues noted in passing:

A. when I disable MS for the site, it pops up 'If there's an issue with the page, please report it so it can get fixed for everybody. [ Report an issue ]' -- clicking this button opens the browser 'store' entry for MS.  In this case, https://addons.opera.com/en/extensions/details/modern-scroll/.  I expected it to go to https://github.com/Christoph142/modern-scroll/issues

B. as I was testing in 'incognito', I had set Opera to allow MS in incognito mode.  Then MS worked, and I was able to operate its options menu, including loading different sets of options (didn't try saving).  However, the option to enable / disable MS on that site is missing.  Fortunately I could toggle it from a not-incognito tab of the same site, and the incognito tab would follow suit

**Comment by Christoph142** [comment]
Hi Bela, thanks for reporting this to me. I can reproduce it and I have a fix for it as well. :)
Regarding A: The links are different depending which version you install. If you install it via the Opera Store, then the link will point there. This is fine and intended.
B: This is by design. For privacy reasons it's not possible for an extension to get the URL of the page in private windows. Hence modern scroll can only be toggled for a page in normal windows.

**Comment by filbo** [comment]
Just to be clear: you intentionally have the 'report an issue' link go to the browser 'store' rather than github issues?  I'd expect that half the users landing there would just spit out a 1-star review, seems like an undesirable feedback loop...

**Comment by Christoph142** [comment]
So far modern scroll's ratings are very good and nobody gave a 1 star review because of a single page that didn't work. It's easier for most users as they typically rather posses an account on the store where they downloaded the extension than on GitHub.
