### ISSUE TITLE
scroll bar to left + edge vertical tab

### ISSUE THREAD

**Issue by ghost** [Christoph142/modern-scroll#214]
the scrollbar is not showing when microsoft edge vertical tab auto show from collapsed to full width.
Idea：scroll bar to left + edge vertical tab
Why：click each tab and scroll a few line is super fast and convenient.

**Comment by Christoph142** [comment]
Hi @zhenjie1999, I'm not entirely sure I get your idea. You can change the location of the vertical scroll bar from right to left if you want in modern scroll's settings already. Does this solve your issue?
