### ISSUE TITLE
Chrome 114.0.5735.110 broke context menus when modern scroll is enabled

### ISSUE THREAD

**Issue by Neuroburst** [Christoph142/modern-scroll#215]
When modern scroll is active:
![image](https://github.com/Christoph142/modern-scroll/assets/69093127/f025dcb0-a572-4b20-b30c-612b55673f0e)

When it is inactive:
![image](https://github.com/Christoph142/modern-scroll/assets/69093127/3c62caa4-490f-4f40-baa7-e73d8d3cee2e)

Only disabling modern scroll fixes the weird missing area of the context menu... Please fix this issue (makes it mostly unusable)

**Comment by Christoph142** [comment]
Indeed. It's a known Chromium Issue. You can vote for https://bugs.chromium.org/p/chromium/issues/detail?id=1346736 in order to get this fixed.

**Comment by Christoph142** [comment]
Just for the record: nothing gets unusable. It's just an empty unnecessary section in the context menu.

**Comment by Neuroburst** [comment]
Maybe rather than making invisible, you could just only add the element once you want to show it? (I think uBlock Origin does this because it does not break the context menu)

**Comment by Christoph142** [comment]
I tried something different: fixing the issue in Chromium directly myself: https://chromium-review.googlesource.com/c/chromium/src/+/4624047
Let's see if I can get it approved. 🤞

**Comment by Neuroburst** [comment]
Good luck!

**Comment by Christoph142** [comment]
If I didn't break anything, it will be fixed in Chromium 117: https://chromiumdash.appspot.com/commit/0ad0f3bd659d227da84dc3051dc4b18e265d66a0 👍

**Comment by Christoph142** [comment]
@Neuroburst can you confirm it's fixed in latest stable Chrome? :)

**Comment by Neuroburst** [comment]
yes it's fixed! 🎉
