### ISSUE TITLE
I want to hide the scrollbar and the background bar like all the stuff, how can I set up?

### ISSUE THREAD

**Issue by SNANA51832** [Christoph142/modern-scroll#220]

**Comment by Christoph142** [comment]
You mean no interface at all?
Or disable on a specific page, because you need to access an element that gets covered?

**Comment by SNANA51832** [comment]
Yes, I mean no interface at all, hope that you can add an option.

**Comment by Christoph142** [comment]
![image](https://github.com/Christoph142/modern-scroll/assets/1440823/2404b622-8383-467f-9c49-4f9aecdfe479)
should do the trick

**Comment by SNANA51832** [comment]
> ![image](https://private-user-images.githubusercontent.com/1440823/294757763-2404b622-8383-467f-9c49-4f9aecdfe479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MzE5MzcsIm5iZiI6MTcwNDYzMTYzNywicGF0aCI6Ii8xNDQwODIzLzI5NDc1Nzc2My0yNDA0YjYyMi04MzgzLTQ2N2YtOWM0OS00ZjlhZWNkZmU0NzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMTI0NzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjBjZTgwY2JjZDkyYTMwNGE3NTc0YTVmYjc1ZjIzNWIwMWNlMDYwMGRlNjNkM2RlNmRiMGFjMWI3ODNkMWIzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P45cLDgoUx85acaQix11s6oHlrOQeuOrSeUiAiXqDOE) should do the trick

OK，thank you.
