### ISSUE TITLE
can it Identify the scrollbar of the word search panel of a translation plugin        

### ISSUE THREAD

**Issue by PiscesDreamer** [Christoph142/modern-scroll#223]
Hello author! I would like to request an adaptation function from you.
I am using Saladict, a translation plugin. After selecting the text, you can call up the word search panel by clicking the icon that appears in the upper right corner of the text.
I really like using your plug-in, but when I use the mouse wheel, I find that I cannot scroll the content in the word search panel through the wheel.

**Comment by Christoph142** [comment]
Sorry, but I can't figure out what the issue is. Translator didn't yield anything useful. Could you try reporting it in English?

**Comment by PiscesDreamer** [comment]
> Sorry, but I can't figure out what the issue is. Translator didn't yield anything useful. Could you try reporting it in English?

I'm very sorry! I was in such a hurry while typing that I sent my draft straight away

**Comment by PiscesDreamer** [comment]
When I move the mouse into the word search panel and use the scroll wheel to scroll the content above, the content of the web page is still scrolled.
This is a very painful thing for me, because as you can see, I have to manually drag the very thin scroll bar to scroll the content of the word search panel.
![PixPin_2024-01-06_00-56-11](https://github.com/Christoph142/modern-scroll/assets/81842690/033e2edd-c2bc-444c-84c1-cbb3d0c5b5aa)

**Comment by Christoph142** [comment]
No worries. Thanks for the details. The screencast also makes it easier to understand. I'm going to have a look. 👍
You should be able to fix it immediately by disabling the custom scrolling functions in modern scroll, though, if you want to. 😉

**Comment by PiscesDreamer** [comment]
> So it turns out that modern scroll simply doesn't have access to Saladict's popup. Unfortunately, in other words: there's nothing I can do about this scrolling issue. 😕 The setting I mentioned earlier does fix it, though (because in that case, the browser does take over the scrolling and the browser of course does have access).

Thank you for your reply!
Is it possible to pause modern scroll when saladict's word search panel appears on the web page, and then restart modern scroll when the panel disappears?

**Comment by PiscesDreamer** [comment]
Maybe I'm a little too lazy to even want to disable modern scroll manually, but if you can provide a faster way to disable it, such as simply providing a button on the page, that should solve my problem. I really like your extension, it saves my fragile wrists and makes browsing the web more convenient.

**Comment by Christoph142** [comment]
I think, you misunderstood. All you need to do is flip that setting to "off":
![image](https://github.com/Christoph142/modern-scroll/assets/1440823/4231c32c-de85-476b-b419-1aff26998775)
You  need to do this exactly once and won't ever have to touch it again. You can keep modern scroll running and Saladict will scroll.
