### ISSUE TITLE
When other extensions or tampermonkey scripts call out pop-ups, can extensions be automatically disabled?  

### ISSUE THREAD

**Issue by PiscesDreamer** [Christoph142/modern-scroll#227]
I found out a long time ago that the control of the scroll bar of the pop-up window cannot be obtained. 
This is a big problem for me, so I want to ask the author whether modern scroll can be automatically banned after the pop-up window appears.    
Will it be difficult to implement? If so, you can ignore my feedback. Thank you for your extension. I use it very conveniently.

**Comment by Christoph142** [comment]
Hi there, I didn't understand the issue yet. Could you elaborate?
You're opening an extension popup and then...?
There's an issue with the page or the popup itself...?
What would you like to achieve or fix?
Maybe add a screenshot if it helps.

**Comment by PiscesDreamer** [comment]
> Hi there, I didn't understand the issue yet. Could you elaborate? You're opening an extension popup and then...? There's an issue with the page or the popup itself...? What would you like to achieve or fix? Maybe add a screenshot if it helps.你好，我还没明白这个问题。 你能详细说明一下吗？ 您正在打开扩展弹出窗口，然后...？ 页面或弹出窗口本身有问题......？ 您想实现或解决什么问题？ 如果有帮助的话也许可以添加屏幕截图。
![Clip_20240401_194955](https://github.com/Christoph142/modern-scroll/assets/81842690/3c881272-dc6e-48c0-bd00-0a27d04d9c18)

**Comment by Christoph142** [comment]
You forgot to write any explanation. I still don't get the issue from the screencast alone. Does the popup fail to scroll?

**Comment by PiscesDreamer** [comment]
> You forgot to write any explanation. I still don't get the issue from the screencast alone. Does the popup fail to scroll?

Yes, as shown in the screenshot, the scroll bars of most pop-ups can't be controlled by the scroll wheel as usual.  
![PixPin_2024-04-01_21-02-34](https://github.com/Christoph142/modern-scroll/assets/81842690/195e749d-ce56-45ad-a1bb-a3258b846550)

**Comment by Christoph142** [comment]
Got it. Thanks. I have a potential fix for it. Gonna test it a bit more, but it's looking good. 🙂
