### ISSUE TITLE
Feature Request: Scrollbar Markers

### ISSUE THREAD

**Issue by Krysl** [Christoph142/modern-scroll#228]
![modern scroll ](https://github.com/Christoph142/modern-scroll/assets/5905801/c9b1f959-4a87-4364-83b1-774d3dcf332b)

**Comment by Christoph142** [comment]
Hi there,
as much as I'd love to see this myself, this is simply not possible for an extension as of today.
I'm keeping an eye on it, though. In case it will be possible at some point, I'll add it.
