### ISSUE TITLE
Interfering with WordPress theme editing.

### ISSUE THREAD

**Issue by givver** [Christoph142/modern-scroll#229]
I just discovered a strange bug when trying to edit my Wordpress Theme Patterns.
When Modern Scroll is enabled I cannot use the space bar.  In Wordpress, I click on Appearence, Editor, Patterns, Footer then click on the Footer to edit it.  When I click on any text I can type anything except a Space.  When I press the space bar nothing happens, when I press any other key on the keyboard, it works fine.  If I disable Modern Scroll the space bar works again.

This is a very strange and specific bug.  It took me a while to determine that Modern Scroll was causing it but after multiple Enables and Disables, the bug is easily reproducible.

**Comment by Christoph142** [comment]
Hi there, thanks for reporting. Do you have a public URL for me where I can reproduce the issue?
For the time being you can disable custom scrolling functions for the keyboard in settings (for this site only or globally) to fix it.

**Comment by givver** [comment]
I would need to give you a login so you can edit a template to see what is happening.  How do I send you a private message with the login?

**Comment by Christoph142** [comment]
If it doesn't contain any private info, you could also save the page and send it to me here. All I need to do is have a look at the structure and elements involved in the editor field. This has to be a custom implementation that modern scroll (so far) can't detect.

**Comment by givver** [comment]
Here is the source for a page where the space bar is not working.
[page_source_space_not_working.zip](https://github.com/user-attachments/files/16922386/page_source_space_not_working.zip)

**Comment by Christoph142** [comment]
Unfortunately the page doesn't contain the editor. 🫤
If you are comfortable sharing it, you can send me the credentials instead to my username at gmx.com

**Comment by Christoph142** [comment]
Never mind. I found https://wordpress.org/gutenberg/ which reproduces the issue. I'll have a look. 🙂

**Comment by Christoph142** [comment]
Will be fixed in the next update. Again, thanks for reporting this to me @givver! 🙌
