### ISSUE TITLE
Two scroll bars in options page

### ISSUE THREAD

**Issue by bratukham** [Christoph142/modern-scroll#51]
![screenshot 2015-02-02 06 07 58](https://cloud.githubusercontent.com/assets/1413357/5996089/448473cc-aaa2-11e4-9f3d-7e6e0b030570.png)

Chrome Version 40.0.2214.94 m

**Comment by Christoph142** [comment]
Good catch!
I would have never gotten that as I'm still suffering from this Chromium issue in latest Opera dev:
https://code.google.com/p/chromium/issues/detail?id=451419
