### ISSUE TITLE
Behavior like in MS Office Word 2013 during the mouse wheel/drag scrolling.

### ISSUE THREAD

**Issue by bratukham** [Christoph142/modern-scroll#52]

**Comment by Christoph142** [comment]
I need more details here. Is that happening now or is it a feature request? And what does MS Word do exactly? ^^

**Comment by bratukham** [comment]
Feature request.

Example: https://www.youtube.com/watch?v=8Y-ClZ4E2_g#t=169 (2:50-2:56)

But you need to try it by yourself to understand it deeply :) It's really cool!

**Comment by Christoph142** [comment]
So you basically want this: https://chrome.google.com/webstore/detail/scrollbar-of-contents/cfmkncejaemmcobmaabfigljmnkeecdm but in one place...? ;)

**Comment by bratukham** [comment]
no-no, I'm mean just the scrolling behavior.
You just move scrollbar by mouse, but the content scrolls a little bit slower and has deceleration at the end.
Just install Express Office 2013 and try it by youself. You will understand what I mean :)

**Comment by Christoph142** [comment]
Oh. Now I gotcha. I do have MS Office 2013 installed myself, so I know it's nice. But it's not that easy to replicate this behavior in JavaScript. There are various smooth scrolling extensions out there that you can use for this purpose. I believe this particular behavior is called "inertia scrolling". You can use those extensions together with modern scroll. Just disable its custom scrolling functions and the other extension will take over this job ;)
