### ISSUE TITLE
Opportunity to add sites to the "white list"

### ISSUE THREAD

**Issue by bratukham** [Christoph142/modern-scroll#54]
It would be nice to have an opportunity to add some sites to "white list". The extension should not be run on the sites from this list. Or at least not use the own customization and left just the custom behavior, like smooth scrolling, etc.

**Comment by Christoph142** [comment]
What you want is a blacklist not a whitelist.
It has been requested before. See:
https://addons.opera.com/en/extensions/details/modern-scroll/?display=en&reports&resolved#r111745-thread

**Comment by bratukham** [comment]
It is perfect, that you can hardcode all sites, that I will send to you, but it really would be more efficient to give this opportunity to the user side.

**Comment by Christoph142** [comment]
I had this in another extension of mine. I really don't wanna go down that road again. Besides I didn't find a single site where modern scroll isn't working and you can always right-click it and hide it.
