### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by mbratukha** [Christoph142/modern-scroll#55]
![unbenannt](https://cloud.githubusercontent.com/assets/1413357/6044023/e4f17aae-ac90-11e4-9c4a-85583a62ce1d.PNG)

chrome-extension://aoabiihlemoajbnjkoocgiffinfieppf/includes/modern_scroll.js:466

**Comment by Christoph142** [comment]
Which site did you get this error on?
Any repro steps?

**Comment by Christoph142** [comment]
Closing this issue as it's reeeeaaaaally old.
